CREATE TABLE volunteers (
V_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
V_NAME VARCHAR(30) NOT NULL,
V_DOB VARCHAR(30) NOT NULL,
V_EMAIL VARCHAR(50) NOT NULL,
V_GENDER VARCHAR(20) NOT NULL,
V_PHONE VARCHAR(50) NOT NULL,
V_CAUSE VARCHAR(50) NOT NULL
);

CREATE TABLE admin (
  A_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  A_NAME VARCHAR(50) NOT NULL,
  A_USERID VARCHAR(50) NOT NULL
);

CREATE TABLE events ( 
  E_ID INT(6) UNSIGNED PRIMARY KEY,
  E_NAME VARCHAR(30) NOT NULL,
  E_DATE VARCHAR(30) NOT NULL,
  E_PLACE VARCHAR(20) NOT NULL,
  E_TIME VARCHAR(20) NOT NULL,
  ADMIN_ID INT(6) UNSIGNED NOT NULL,
  FOREIGN KEY (ADMIN_ID) REFERENCES admin(A_ID)
);

CREATE TABLE sponsor(
 S_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 S_NAME VARCHAR(50) NOT NULL,
 S_EMAIL VARCHAR(50) NOT NULL,
 S_CAUSE VARCHAR(50) NOT NULL,
 S_AMOUNT INT(100) NOT NULL,
 ADMIN_ID INT(6) UNSIGNED NOT NULL,
 FOREIGN KEY (ADMIN_ID) REFERENCES admin(A_ID) 
);

CREATE TABLE volunteers_for (
 VOLUNTEER_ID INT(6) UNSIGNED NOT NULL,
 EVENT_ID INT(6) UNSIGNED NOT NULL,
 FOREIGN KEY (VOLUNTEER_ID) REFERENCES volunteers(V_ID),
 FOREIGN KEY (EVENT_ID) REFERENCES events(E_ID)
);

ALTER TABLE events CHANGE E_ID E_ID INT(6) UNSIGNED NOT NULL;

CREATE TABLE feedback(
FEEDBACK_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) NOT NULL,
COMMENTS VARCHAR(50) NOT NULL
);

